version: '3.8'
services:
  tech_bot:
    image: skyline8880/tech_scheduler_service:latest
    container_name: tech_scheduler_service
    restart: on-failure
    environment:
      - TZ=Europe/Moscow
    env_file:
      - .env
    ports:
      - 86:8887