name: TechScheduler workflow #автоматизация проверки качества кода и сборки образа Docker в Docker Hub

on:
  push:

jobs:
  check_code:
    name: Check Code Quality #проверка качества кода
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v4' #получение кода репозитория
      - name: Install Python 3.11 #устанавливается Python версии 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: | #устанавливаются зависимости, обновляется pip и устанавливаются пакеты из requirements.txt
          python -m pip install --upgrade pip
          pip install -r requirements.txt      
      - name: Run flake8
        run: flake8 . # проверка стиля
  build_and_push_to_docker_hub:
    needs: check_code # если этап завершен успешно идем дальше
    name: Push Docker image to Docker Hub # отправка образа Docker в Docker Hub
    runs-on: ubuntu-latest # Задача выполняется на Ubuntu и если изменения внесены в ветку master или main
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 #для настройки Docker Buildx
      - name: Login to Docker
        uses: docker/login-action@v3 #для входа в учетную запись Docker с использованием секретов
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v5 #сборка образа и отправки в Docker Hub. 
        
        with:
          context: ./ # Контекст и файл для сборки определяются текущим каталогом
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tech_scheduler_service